export const data = [
  {
    id: "1",
    soLuuCV: "123",
    soCVDi: "123/DTHU",
    trichYeu: "Báo cáo công tác",
    loaiVanBan: "Văn bản hành chính",
    trangThai: "0",
    coQuanNhan: "Cơ quan hành chính",
    ngayNhap: "25/5/2022",
  },
  {
    id: "2",
    soLuuCV: "456",
    soCVDi: "456/DTHU",
    trichYeu: "Báo cáo công tác",
    loaiVanBan: "Văn bản hành chính",
    trangThai: "1",
    coQuanNhan: "Cơ quan hành chính",
    ngayNhap: "25/5/2022",
  },
  {
    id: "3",
    soLuuCV: "789",
    soCVDi: "789/DTHU",
    trichYeu: "Báo cáo công tác",
    loaiVanBan: "Văn bản ban hành",
    trangThai: "2",
    coQuanNhan: "Cơ quan hành chính",
    ngayNhap: "25/5/2022",
  },
];
